name: StartServer

on:
  repository_dispatch:
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: JellyfinServer
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Jellyfin Install
        run: |
          sudo apt install aria2
          sudo aria2c --enable-rpc --rpc-listen-all --daemon
          sudo apt install apt-transport-https
          wget -O - https://repo.jellyfin.org/jellyfin_team.gpg.key | sudo apt-key add -
          echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
          sudo apt update
          sudo apt install jellyfin
          sudo systemctl stop jellyfin
          sudo rm -r /var/lib/jellyfin
          sudo rm -r /etc/jellyfin
          sudo cp -R /home/runner/work/jellyfintest/jellyfintest/jellyfinconf/lib/jellyfin /var/lib/
          sudo cp -R /home/runner/work/jellyfintest/jellyfintest/jellyfinconf/etc/jellyfin /etc/
          sudo chmod 755 -R /var/lib/jellyfin/
          sudo chown -R jellyfin:jellyfin /etc/jellyfin/
          sudo chmod 755 -R /etc/jellyfin/
          sudo chown -R jellyfin:jellyfin /var/lib/jellyfin/
          mkdir cloudflare
          cd cloudflare
          wget https://github.com/cryptbphcoutlook/test123/raw/main/cloudflare/cloudflared-stable-linux-amd64.deb
          sudo dpkg -i cloudflared-stable-linux-amd64.deb
          cd ..
          cd ~/
          mkdir .cloudflared
          cd .cloudflared
          cat << EOF >> cert.pem
          ${{ secrets.CF_CERT }}
          EOF
          cd ..
          sudo systemctl start jellyfin
          timeout 4m cloudflared --url localhost:8096 --hostname ${{ secrets.JELLYFIN_DOMAIN }} || ( [[ $? -eq 124 ]] && \echo "WARNING: Timeout reached for Jellyfin, but that's OK" )  & timeout 4m cloudflared --url localhost:6800 --hostname ${{ secrets.ARIA2_DOMAIN }} || ( [[ $? -eq 124 ]] && \echo "WARNING: Timeout reached for aria2, but that's OK" )
          sudo systemctl stop jellyfin
          cloudflared tunnel delete -f jellyfin
          sudo rm -r /home/runner/work/jellyfintest/jellyfintest/jellyfinconf/
          mkdir jellyfinconf
          cd jellyfinconf
          mkdir etc
          mkdir lib
          cd lib
          sudo cp -R /var/lib/jellyfin /home/runner/work/jellyfintest/jellyfintest/jellyfinconf/lib/
          cd ..
          cd etc
          sudo cp -R /etc/jellyfin /home/runner/work/jellyfintest/jellyfintest/jellyfinconf/etc/
          cd ..
          sudo git config --global user.name 'cryptbphcoutlook'
          sudo git config --global user.email 'cryptbphcoutlook@users.noreply.github.com'
          sudo git add .
          sudo git commit -am "Config File"
          sudo git push
          
          
                    
